SRT社团介绍添加
camera-2018/hdu-cs-wiki pull request #55
Opened 2023-07-14 14:07 UTC by creamm-kk

2023-07-14 14:07 UTC, creamm-kk commented
这是来自QQ邮箱的假期自动回复邮件。你好，我已收到您的邮件，我的联系方式是19357380085。

2023-07-14 14:08 UTC, camera-2018 commented
这是来自QQ邮箱的假期自动回复邮件。你好，我已收到您的邮件，我的联系方式是原神。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "camera-2018/hdu-cs-wiki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 晚上10:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [camera-2018/hdu-cs-wiki] SRT社团介绍添加 (PR #55)





 这是来自QQ邮箱的假期自动回复邮件。你好，我已收到您的邮件，我的联系方式是19357380085。 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2023-07-14 14:11 UTC, camera-2018 requested changes

2023-07-14 14:11 UTC, camera-2018 commented on .vitepress/config.js
> +          { text: 'SRT社团介绍', link: '/4.人工智能/SRT.md' },
link不需要md后缀

2023-07-14 14:11 UTC, camera-2018 commented on 4.人工智能/SRT.md
> +![](https://cdn.nlark.com/yuque/0/2023/jpeg/432943/1689342819938-af714fea-814f-499c-bbe3-ef0e3f105185.jpeg#averageHue=%239ba2a3&clientId=u2dadd124-e8b6-4&from=paste&id=ub10883f6&originHeight=1280&ori
语雀的图片我们加载不出来的 你添加到图片文件夹里

2023-07-14 14:14 UTC, creamm-kk commented on 4.人工智能/SRT.md
> +![](https://cdn.nlark.com/yuque/0/2023/jpeg/432943/1689342819938-af714fea-814f-499c-bbe3-ef0e3f105185.jpeg#averageHue=%239ba2a3&clientId=u2dadd124-e8b6-4&from=paste&id=ub10883f6&originHeight=1280&ori
我正在加，稍等

2023-07-14 14:14 UTC, creamm-kk commented on 4.人工智能/SRT.md
> +![](https://cdn.nlark.com/yuque/0/2023/jpeg/432943/1689342819938-af714fea-814f-499c-bbe3-ef0e3f105185.jpeg#averageHue=%239ba2a3&clientId=u2dadd124-e8b6-4&from=paste&id=ub10883f6&originHeight=1280&ori
我先回寝室了，如果不行的话我明天再搞

2023-07-14 15:06 UTC, merged

2024-05-28 13:01 UTC, camera-2018 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/camera-2018/hdu-cs-wiki/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: